runtime: nodejs22
env: standard

env_variables:
  DB_URI: "mongodb+srv://kumarkas1515:8P1T3d9HaHSD3FiW@cluster0.5yjlgi1.mongodb.net/muta-engine"
  EMAIL_USER: "kumarkas1515@gmail.com"
  EMAIL_PASS: "eaesoevofpynphhs"
  RECAPTCHA_SITE_KEY: "6LeQF0sqAAAAAMwq0oSP5Ah7rrqBY_7HPXOvF54_"
  RECAPTCHA_SECRET_KEY: "6LeQF0sqAAAAAPnXUIsWbOCOsM0T-_-pkNj8czK-"
  STRIPE_SECRET_KEY: "sk_test_51Q1TTsA0O279fsHGesqmkM6GBVQHH9i4d2ZdqICVSoFfCwBULFcBaJYhqIZXaDZZqfpndXljneb4wy07sOxK9gXW00E1Wf8PQ8"
  JWT_SECRET: "123456"
  X_API_KEY: "abcd@1234"
  FRONTEND_URL: "http://localhost:3000"
  STRIPE_WEBHOOK_SECRET: "whsec_vrjSojnp23pIZclys7N4JwoKdBGSiwiN"

handlers:
  - url: /.*
    script: auto
